### ISSUE TITLE
Unable to use image variable for itemsadder

### ISSUE THREAD

**Issue by StealthDeci** [casperge/RealisticSeasons-issues#226]
For example, SEASON-TO-WINTER: '%img_winter%&b&l Winter has begun!'
Not a real image, but a simple "%img_winter%"

**Comment by StealthDeci** [comment]
And using %rs-air_temperaturecolor% will not yield any results

**Comment by Mitality** [comment]
Go to `plugins/ItemsAdder/contents/<namespace>/configs/` and look for a file containing something like this:
```
font_images:
  example_font_image:
    path: <namespace>/somelocation/image
    y_position: 8
    scale_ratio: 10
    symbol: 뀁
```
Look for a `img_winter` and copy the corresponding `symbol`.

(optional) Paste the symbol in your MC chat to ensure it's displayed as the image there.

Use the symbol instead of %img_winter% in your config.
